[tool.poetry]
name = "aoc-2022"
version = "0.1.0"
description = "Advent Of Code"
authors = ["Robin <delcrorn@skysoft-atm.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
